name: MCTag
version: 1.1
main: me.hawkfalcon.mctag.MCTag      
permissions:  
    MCTag.notele.bypass:
       description: Allows bypass of no teleporting
       default: OP
       
    MCTag.nocommands.bypass:
       description: Allows bypass of no commands
       default: OP
       
